#!/bin/bash
# Execute the JSON matrix generated by input_dimensions.py against one matched
# before/after binary pair. Commands are generated or reviewed test artifacts;
# run this script only inside the isolated test environment selected by the skill.

set -euo pipefail

TIMEOUT_SEC=30
INPUTS_FILE=""
BEFORE_DIR=""
AFTER_DIR=""
OUTPUT_DIR=""

while [ $# -gt 0 ]; do
    case "$1" in
        --inputs) INPUTS_FILE="$2"; shift 2 ;;
        --before-dir) BEFORE_DIR="$2"; shift 2 ;;
        --after-dir) AFTER_DIR="$2"; shift 2 ;;
        --output) OUTPUT_DIR="$2"; shift 2 ;;
        --timeout) TIMEOUT_SEC="$2"; shift 2 ;;
        *) echo "Unknown option: $1" >&2; exit 1 ;;
    esac
done

for arg in INPUTS_FILE BEFORE_DIR AFTER_DIR OUTPUT_DIR; do
    if [ -z "${!arg}" ]; then
        echo "Error: --${arg,,} is required" >&2
        exit 1
    fi
done

if [ ! -f "$INPUTS_FILE" ]; then
    echo "Error: inputs file not found: $INPUTS_FILE" >&2
    exit 1
fi

mkdir -p "$OUTPUT_DIR"
RESULTS_FILE="$OUTPUT_DIR/matrix_results.jsonl"
: > "$RESULTS_FILE"

AFTER_BIN=""
for candidate in "$AFTER_DIR"/*; do
    if [ -f "$candidate" ] && [ -x "$candidate" ]; then
        AFTER_BIN="$candidate"
        break
    fi
done

BEFORE_BIN=""
if [ -n "$AFTER_BIN" ]; then
    binary_name=$(basename "$AFTER_BIN")
    if [ -f "$BEFORE_DIR/$binary_name" ] && [ -x "$BEFORE_DIR/$binary_name" ]; then
        BEFORE_BIN="$BEFORE_DIR/$binary_name"
    fi
fi

echo "=== Input Dimension Matrix Execution ==="
echo "Inputs: $INPUTS_FILE"
echo "Before: ${BEFORE_BIN:-<not available>}"
echo "After:  ${AFTER_BIN:-<not available>}"

TOTAL=0
EXECUTED=0
DIFF_FOUND=0
SKIPPED=0

decode_field() {
    printf '%s' "$1" | base64 --decode
}

write_result() {
    python3 - "$@" >> "$RESULTS_FILE" <<'PY'
import json
import sys

print(json.dumps({
    "finding_id": sys.argv[1],
    "compatibility_type": sys.argv[2],
    "input_id": sys.argv[3],
    "dimension": sys.argv[4],
    "command": sys.argv[5],
    "cwd": sys.argv[6],
    "status": sys.argv[7],
    "after_rc": int(sys.argv[8]),
    "before_rc": int(sys.argv[9]),
    "diff_found": sys.argv[10] == "true",
    "diff_type": sys.argv[11],
    "reason": sys.argv[12],
}, ensure_ascii=False))
PY
}

while IFS='|' read -r fid64 type64 iid64 dim64 cmd64 cwd64; do
    finding_id=$(decode_field "$fid64")
    finding_type=$(decode_field "$type64")
    input_id=$(decode_field "$iid64")
    dim_name=$(decode_field "$dim64")
    cmd_template=$(decode_field "$cmd64")
    execution_cwd=$(decode_field "$cwd64")
    execution_cwd=${execution_cwd:-$PWD}
    TOTAL=$((TOTAL + 1))

    if [ -z "$cmd_template" ]; then
        echo "  SKIP [$input_id] Planned type axis requires a finding-specific probe"
        write_result "$finding_id" "$finding_type" "$input_id" "$dim_name" "$cmd_template" "$execution_cwd" \
            "SKIP" -1 -1 false "NONE" "planned_needs_probe"
        SKIPPED=$((SKIPPED + 1))
        continue
    fi

    requires_binary=false
    if [[ "$cmd_template" == *BINARY* ]]; then
        requires_binary=true
    fi

    if [ "$requires_binary" = true ] && [ -z "$AFTER_BIN" ]; then
        echo "  SKIP [$input_id] No executable in after dir"
        write_result "$finding_id" "$finding_type" "$input_id" "$dim_name" "$cmd_template" "$execution_cwd" \
            "SKIP" -1 -1 false "NONE" "no_after_binary"
        SKIPPED=$((SKIPPED + 1))
        continue
    fi

    if [ ! -d "$execution_cwd" ]; then
        echo "  SKIP [$input_id] Invalid cwd: $execution_cwd"
        write_result "$finding_id" "$finding_type" "$input_id" "$dim_name" "$cmd_template" "$execution_cwd" \
            "SKIP" -1 -1 false "NONE" "invalid_cwd"
        SKIPPED=$((SKIPPED + 1))
        continue
    fi

    after_cmd="$cmd_template"
    before_cmd=""
    if [ "$requires_binary" = true ]; then
        after_cmd=${cmd_template//BINARY/$AFTER_BIN}
        if [ -n "$BEFORE_BIN" ]; then
            before_cmd=${cmd_template//BINARY/$BEFORE_BIN}
        fi
    fi
    echo "  [$input_id] Executing: ${after_cmd:0:80}"

    set +e
    after_out=$(cd "$execution_cwd" && timeout "$TIMEOUT_SEC" bash -c "$after_cmd" </dev/null 2>&1)
    after_rc=$?
    before_out=""
    before_rc=-1
    if [ -n "$before_cmd" ]; then
        before_out=$(cd "$execution_cwd" && timeout "$TIMEOUT_SEC" bash -c "$before_cmd" </dev/null 2>&1)
        before_rc=$?
    fi
    set -e

    EXECUTED=$((EXECUTED + 1))
    diff_found=false
    diff_type="NONE"
    if [ "$before_rc" -ge 0 ] && { [ "$before_out" != "$after_out" ] || [ "$before_rc" -ne "$after_rc" ]; }; then
        diff_found=true
        DIFF_FOUND=$((DIFF_FOUND + 1))
        diff_type="$finding_type"
        echo "    DIFF: $diff_type (RC: $before_rc -> $after_rc)"
    fi

    write_result "$finding_id" "$finding_type" "$input_id" "$dim_name" "$cmd_template" "$execution_cwd" \
        "EXECUTED" "$after_rc" "$before_rc" "$diff_found" "$diff_type" ""
done < <(
    python3 - "$INPUTS_FILE" <<'PY'
import base64
import json
import sys

def enc(value):
    return base64.b64encode(str(value).encode("utf-8")).decode("ascii")

with open(sys.argv[1], encoding="utf-8") as handle:
    data = json.load(handle)
for finding in data.get("findings", []):
    finding_id = finding.get("id", "UNKNOWN")
    finding_type = finding.get("type", "UNKNOWN")
    for dimension, inputs in finding.get("dimensions", {}).items():
        for item in inputs:
            print("|".join(enc(value) for value in (
                finding_id,
                finding_type,
                item.get("input_id", "I0"),
                dimension,
                item.get("command", ""),
                item.get("cwd", ""),
            )))
PY
)

status="NO_DIFFS"
if [ "$DIFF_FOUND" -gt 0 ]; then
    status="DIFFS_DETECTED"
elif [ "$EXECUTED" -eq 0 ]; then
    status="NOT_EXECUTED"
fi

python3 - "$TOTAL" "$EXECUTED" "$DIFF_FOUND" "$SKIPPED" "$status" \
    > "$OUTPUT_DIR/matrix_summary.json" <<'PY'
import json
import sys

print(json.dumps({
    "total_inputs": int(sys.argv[1]),
    "executed": int(sys.argv[2]),
    "diff_found": int(sys.argv[3]),
    "skipped": int(sys.argv[4]),
    "status": sys.argv[5],
}, indent=2))
PY

echo ""
echo "=== Matrix Execution Summary ==="
echo "Total inputs:  $TOTAL"
echo "Executed:      $EXECUTED"
echo "Diffs found:   $DIFF_FOUND"
echo "Skipped:       $SKIPPED"
echo "Results: $RESULTS_FILE"
echo "Summary: $OUTPUT_DIR/matrix_summary.json"
